name: Build and Publish Data Dictionary

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CONFLUENCE_LOGIN: ${{ secrets.CONFLUENCE_LOGIN }}
      CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
      CONFLUENCE_URL: ${{ vars.CONFLUENCE_URL }}
      CONFLUENCE_PAGE_TITLE: ${{ env.CONFLUENCE_PAGE_TITLE }}
      CONFLUENCE_PARENT_PAGE_ID: ${{ env.CONFLUENCE_PARENT_PAGE_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Publish to Confluence
      run: python src/main/resources/scripts/postToConfluence.py